name: Auto-merge Dependabot updates

on:
  pull_request_target:

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Auto-merge for Dependabot
        uses: peter-evans/auto-merge@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
          author-email: 'dependabot[bot]@users.noreply.github.com'
          author-name: 'dependabot[bot]'
          commit-message: 'chore: merge dependabot updates'