name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10", 3.11]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
    - name: Test Python syntax
      run: |
        python -m py_compile src/cipher_decoder.py
        python -m py_compile src/embed_wordlist.py
    - name: Basic functionality test
      run: |
        cd src
        python embed_wordlist.py
        if [ -f "cipher_decoder.py" ]; then
          echo "Files compiled successfully"
        fi