name: 'Close stale issues and PRs'

on:
  schedule:
    - cron: '30 1 * * *'  # Daily at 1:30 AM UTC

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          stale-issue-message: 'This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.'
          stale-pr-message: 'This PR has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.'
          close-issue-message: 'This issue was closed because it has been stalled for 7 days with no activity.'
          close-pr-message: 'This PR was closed because it has been stalled for 7 days with no activity.'
          days-before-stale: 30
          days-before-close: 7
          exempt-issue-labels: 'enhancement,bug,documentation'
          exempt-pr-labels: 'enhancement,bug,documentation'